src/TomorrowDAOServer.Application/DAO/DAOAppService.cs

Fix the issue with the incorrect number of proposals for the Network Dao in the Dao list

---

src/TomorrowDAOServer.Application.Contracts/Proposal/Dto/QueryMyProposalInput.cs
src/TomorrowDAOServer.Application.Contracts/Proposal/Dto/QueryVoteHistoryInput.cs
src/TomorrowDAOServer.Application.Contracts/User/Dtos/UserDto.cs
src/TomorrowDAOServer.Application/Proposal/ProposalService.cs
src/TomorrowDAOServer.Application/Providers/ExplorerProvider.cs
src/TomorrowDAOServer.Application/User/Provider/UserProvider.cs
src/TomorrowDAOServer.Application/User/UserAppService.cs
src/TomorrowDAOServer.AuthServer/Options/AuthConstant.cs
src/TomorrowDAOServer.AuthServer/SignatureGrantHandler.cs
src/TomorrowDAOServer.AuthServer/TomorrowDAOServerAuthServerModule.cs
src/TomorrowDAOServer.AuthServer/apollo.appsettings.json
src/TomorrowDAOServer.DbMigrator/Program.cs
src/TomorrowDAOServer.DbMigrator/TomorrowDAOServer.DbMigrator.csproj
src/TomorrowDAOServer.DbMigrator/appsettings.json
src/TomorrowDAOServer.Domain/Entities/UserIndex.cs
src/TomorrowDAOServer.Domain/TomorrowDAOServerDomainModule.cs
src/TomorrowDAOServer.Grains/Grain/Users/UserGrain.cs
src/TomorrowDAOServer.Grains/Grain/Users/UserGrainDto.cs
src/TomorrowDAOServer.Grains/State/Users/UserState.cs
src/TomorrowDAOServer.HttpApi/Controllers/ProposalController.cs
src/TomorrowDAOServer.Silo/apollo.appsettings.json

1. Generate a login token.
2. Add authentication to the "my-info" and "vote-history" APIs.  #21

login authorization

---

src/TomorrowDAOServer.Application.Contracts/Options/TestDaoOption.cs
src/TomorrowDAOServer.Application/DAO/DAOAppService.cs
src/TomorrowDAOServer.HttpApi.Host/TomorrowDAOServerHttpApiHostModule.cs
src/TomorrowDAOServer.HttpApi.Host/appsettings.json

Hide test DAO

---

src/TomorrowDAOServer.Application.Contracts/Common/AElfSdk/ContractProvider.cs
src/TomorrowDAOServer.Application.Contracts/Common/CommonConstant.cs
src/TomorrowDAOServer.Application.Contracts/Common/Dtos/PageResultDto.cs
src/TomorrowDAOServer.Application.Contracts/DAO/Dtos/MyDAOListDto.cs
src/TomorrowDAOServer.Application.Contracts/DAO/Dtos/QueryDAOListInput.cs
src/TomorrowDAOServer.Application.Contracts/DAO/Dtos/QueryMyDAOListInput.cs
src/TomorrowDAOServer.Application.Contracts/DAO/IDAOAppService.cs
src/TomorrowDAOServer.Application.Contracts/NetworkDao/IElectionService.cs
src/TomorrowDAOServer.Application.Contracts/Options/ChainOptions.cs
src/TomorrowDAOServer.Application.Contracts/Treasury/Dto/GetTreasuryAssetsInput.cs
src/TomorrowDAOServer.Application.Contracts/Treasury/Dto/TreasuryAssertsDto.cs
src/TomorrowDAOServer.Application.Contracts/Treasury/Dto/TreasuryAssetsPagedResultDto.cs
src/TomorrowDAOServer.Application.Contracts/Treasury/ITreasuryAssetsService.cs
src/TomorrowDAOServer.Application/DAO/DAOAppService.cs
src/TomorrowDAOServer.Application/DAO/Provider/DAOProvider.cs
src/TomorrowDAOServer.Application/NetworkDao/ElectionService.cs
src/TomorrowDAOServer.Application/TomorrowDAOServerApplicationAutoMapperProfile.cs
src/TomorrowDAOServer.Application/Treasury/Provider/ITreasuryAssetsProvider.cs
src/TomorrowDAOServer.Application/Treasury/TreasuryAssetsService.cs
src/TomorrowDAOServer.Domain.Shared/Enums/MyDAOType.cs
src/TomorrowDAOServer.Domain/Common/GetParticipatedInput.cs
src/TomorrowDAOServer.HttpApi.Host/TomorrowDAOServerHttpApiHostModule.cs
src/TomorrowDAOServer.HttpApi/Controllers/DaoController.cs
src/TomorrowDAOServer.HttpApi/Controllers/NetworkDaoController.cs
src/TomorrowDAOServer.HttpApi/Controllers/TreasuryControllers.cs
test/TomorrowDAOServer.Application.Tests/DAO/DAOAppServiceTests.cs
test/TomorrowDAOServer.Application.Tests/DAO/DaoAppServiceTest.cs

1. Implement treasury fund inquiry
2. Implement BP election total staking amount inquiry #32

implement treasury module

---

src/TomorrowDAOServer.Application.Contracts/Common/CommonConstant.cs
src/TomorrowDAOServer.Application.Contracts/DAO/Dtos/DAOInfoDto.cs
src/TomorrowDAOServer.Application.Contracts/DAO/Dtos/GetMemberInput.cs
src/TomorrowDAOServer.Application.Contracts/DAO/Dtos/GetMemberListInput.cs
src/TomorrowDAOServer.Application.Contracts/DAO/IDAOAppService.cs
src/TomorrowDAOServer.Application.Contracts/Vote/Dto/GetVoteSchemeInput.cs
src/TomorrowDAOServer.Application/DAO/DAOAppService.cs
src/TomorrowDAOServer.Application/DAO/Provider/DAOProvider.cs
src/TomorrowDAOServer.Application/MapperBase.cs
src/TomorrowDAOServer.Application/Proposal/ProposalService.cs
src/TomorrowDAOServer.Application/Token/TokenService.cs
src/TomorrowDAOServer.Application/TomorrowDAOServerApplicationAutoMapperProfile.cs
src/TomorrowDAOServer.Application/Vote/VoteService.cs
src/TomorrowDAOServer.Domain.Shared/Enums/GovernanceMechanism.cs
src/TomorrowDAOServer.Domain/DAO/DAOIndex.cs
src/TomorrowDAOServer.Domain/DAO/Indexer/IndexerDAOInfos.cs
src/TomorrowDAOServer.Domain/DAO/Indexer/MemberDto.cs
src/TomorrowDAOServer.Domain/Entities/ProposalBase.cs
src/TomorrowDAOServer.HttpApi/Controllers/DaoController.cs
src/TomorrowDAOServer.Worker/TomorrowDAOServerWorkerModule.cs
test/TomorrowDAOServer.Application.Tests/DAO/DAOAppServiceTests.cs
test/TomorrowDAOServer.Application.Tests/DAO/DaoAppServiceTest.cs
test/TomorrowDAOServer.Application.Tests/DAO/Provider/DAOProviderTest.cs
test/TomorrowDAOServer.Application.Tests/Vote/VoteServiceTest.cs

1、Add member-list for organization DAO
2、Add check logic for organization DAO's vote to verify whether an address is member
#36

Implement member module

---

src/TomorrowDAOServer.Application.Contracts/Election/Dto/ElectionCandidateElectedDto.cs
src/TomorrowDAOServer.Application.Contracts/Election/Dto/ElectionGraphqlQueryParams.cs
src/TomorrowDAOServer.Application.Contracts/Election/Dto/ElectionHighCouncilConfigDto.cs
src/TomorrowDAOServer.Application.Contracts/Election/Dto/ElectionPageResultDto.cs
src/TomorrowDAOServer.Application.Contracts/Election/Dto/ElectionVotingItemDto.cs
src/TomorrowDAOServer.Application.Contracts/Election/Dto/HighCouncilMembersInput.cs
src/TomorrowDAOServer.Application.Contracts/Election/IElectionService.cs
src/TomorrowDAOServer.Application/Common/Provider/GraphQLProvider.cs
src/TomorrowDAOServer.Application/Contract/ScriptService.cs
src/TomorrowDAOServer.Application/DAO/DAOAppService.cs
src/TomorrowDAOServer.Application/Election/ElectionService.cs
src/TomorrowDAOServer.Application/Election/HighCouncilMemberSyncService.cs
src/TomorrowDAOServer.Application/Election/Provider/ElectionProvider.cs
src/TomorrowDAOServer.Application/Proposal/ProposalService.cs
src/TomorrowDAOServer.Application/TomorrowDAOServerApplicationModule.cs
src/TomorrowDAOServer.Domain.Shared/Common/ContractConstants.cs
src/TomorrowDAOServer.Domain.Shared/Enums/WorkerBusinessType.cs
src/TomorrowDAOServer.Grains/Grain/Election/HighCouncilMembersGrain.cs
src/TomorrowDAOServer.Grains/State/Election/HighCouncilMembersState.cs
src/TomorrowDAOServer.Grains/TomorrowDAOServer.Grains.csproj
src/TomorrowDAOServer.HttpApi/Controllers/ElectionController.cs
src/TomorrowDAOServer.Worker/Jobs/HighCouncilMemberSyncWorker.cs
src/TomorrowDAOServer.Worker/TomorrowDAOServerWorkerModule.cs
test/TomorrowDAOServer.Application.Tests/Election/HighCouncilMemberSyncServiceTest.cs
test/TomorrowDAOServer.Application.Tests/Election/HighCouncilMemberSyncServiceTestMock.cs
test/TomorrowDAOServer.Application.Tests/TomorrowDAOServerApplicationTestModule.cs

1. Regularly monitor changes in High Council member additions, deletions, and turnover election logs, synchronize the High Council member list to Silo.
2. Add a High Council member query interface.
3. 3. Modify user voting permission verification to query Silo data. #36

High Council Member Management

---

src/TomorrowDAOServer.Application/Proposal/ProposalService.cs
test/TomorrowDAOServer.Application.Tests/Proposal/ProposalServiceTest.cs

1、Convert MinimalRequiredThreshold from percentage to real member count for Organization DAO.
#49

Fix the issue of proposal's governance threshold

---

src/TomorrowDAOServer.Application.Contracts/DAO/Dtos/DAOInfoDto.cs
src/TomorrowDAOServer.Application.Contracts/Governance/Dto/GovernanceSchemeDto.cs
src/TomorrowDAOServer.Application.Contracts/Governance/Dto/IndexerGovernanceSchemeDto.cs
src/TomorrowDAOServer.Application/DAO/DAOAppService.cs
src/TomorrowDAOServer.Domain/Entities/ProposalBase.cs
src/TomorrowDAOServer.Domain/Proposal/Index/IndexerProposalSync.cs

Change the parameter type in the governance mechanism from int to long. #45

Fix the issue of parameter type overflow in the governance mechanism

---

src/TomorrowDAOServer.Application.Contracts/DAO/Dtos/DAOListDto.cs
src/TomorrowDAOServer.Application.Contracts/DAO/Dtos/DaoAliasDto.cs
src/TomorrowDAOServer.Application.Contracts/DAO/Dtos/GetDAOInfoInput.cs
src/TomorrowDAOServer.Application.Contracts/Options/DaoAliasOptions.cs
src/TomorrowDAOServer.Application.Contracts/Options/DaoOptions.cs
src/TomorrowDAOServer.Application.Contracts/Proposal/Dto/ProposalDto.cs
src/TomorrowDAOServer.Application/Common/Provider/GraphQLProvider.cs
src/TomorrowDAOServer.Application/DAO/DAOAppService.cs
src/TomorrowDAOServer.Application/DAO/DAOSyncDataService.cs
src/TomorrowDAOServer.Application/DAO/Provider/DAOProvider.cs
src/TomorrowDAOServer.Application/DAO/Provider/DaoAliasProvider.cs
src/TomorrowDAOServer.Application/Proposal/ProposalService.cs
src/TomorrowDAOServer.Domain/DAO/DAOIndex.cs
src/TomorrowDAOServer.EntityEventHandler/TomorrowDAOServerEntityEventHandlerModule.cs
src/TomorrowDAOServer.EntityEventHandler/appsettings.json
src/TomorrowDAOServer.Grains/Grain/Dao/DaoAliasGrain.cs
src/TomorrowDAOServer.Grains/State/Dao/DaoAliasState.cs
src/TomorrowDAOServer.Grains/TomorrowDAOServerAutoMapperProfile.cs
src/TomorrowDAOServer.HttpApi.Host/TomorrowDAOServerHttpApiHostModule.cs
src/TomorrowDAOServer.Worker/Jobs/BPInfoUpdateWorker.cs
src/TomorrowDAOServer.Worker/Jobs/DAOSyncWorker.cs
src/TomorrowDAOServer.Worker/Jobs/HighCouncilMemberSyncWorker.cs
src/TomorrowDAOServer.Worker/Jobs/ProposalExpiredWorker.cs
src/TomorrowDAOServer.Worker/Jobs/ProposalNewUpdateWorker.cs
src/TomorrowDAOServer.Worker/Jobs/ProposalSyncWorker.cs
src/TomorrowDAOServer.Worker/TomorrowDAOServerWorkBase.cs
test/TomorrowDAOServer.Application.Tests/DAO/DaoAppServiceTest.cs
test/TomorrowDAOServer.Application.Tests/DAO/Provider/DAOProviderTest.cs
test/TomorrowDAOServer.Application.Tests/DAO/Provider/DaoAliasProviderTest.cs
test/TomorrowDAOServer.Application.Tests/DAO/Provider/DaoAliasProviderTestMock.cs

1、When synchronizing DAO data, generate aliases for the DAO
2、Querying the DAO list interface returns DAO aliases.
3、The DAO detail interface supports querying by alias. #44

Optimization urls

---

src/TomorrowDAOServer.Application.Contracts/Options/NetworkDaoOptions.cs
src/TomorrowDAOServer.Application/DAO/Provider/DAOProvider.cs
src/TomorrowDAOServer.Application/MapperBase.cs
src/TomorrowDAOServer.Application/Token/TokenService.cs
src/TomorrowDAOServer.Application/TomorrowDAOServerApplicationAutoMapperProfile.cs
src/TomorrowDAOServer.Application/Treasury/TreasuryAssetsService.cs
src/TomorrowDAOServer.HttpApi.Host/TomorrowDAOServerHttpApiHostModule.cs
src/TomorrowDAOServer.HttpApi.Host/appsettings.json
test/TomorrowDAOServer.Application.Tests/Token/TokenServiceTest.cs

1、Treasury assets's query implement  network DAO related logic.
#59

Treasury asset support networkdao

---

src/TomorrowDAOServer.Silo/Extensions/OrleansHostExtensions.cs

1. Fix the Silo access timeout issue. #71

Fix the unavailability of Silo

---

src/TomorrowDAOServer.Application/Proposal/ProposalService.cs
test/TomorrowDAOServer.Application.Tests/Proposal/ProposalServiceTest.cs

1.Fix can execute logic: proposal stage check modify
close #84

Fix can execute problem

---

src/TomorrowDAOServer.Application/TomorrowDAOServerApplicationModule.cs

Remove duplicated code

---

src/TomorrowDAOServer.Application/Token/TokenService.cs

1.Optimize token price's avg price.
close #99

Token price optimization

---

src/TomorrowDAOServer.Application.Contracts/Options/ExchangeOptions.cs
src/TomorrowDAOServer.Application.Contracts/ThirdPart/Exchange/AwakenProvider.cs
src/TomorrowDAOServer.Application.Contracts/ThirdPart/Exchange/IExchangeProvider.cs
src/TomorrowDAOServer.Application/TomorrowDAOServerApplicationModule.cs
src/TomorrowDAOServer.EntityEventHandler/appsettings.json
test/TomorrowDAOServer.Application.Contracts.Tests/ThirdPart/AwakenProviderTest.cs

Support token price from Awaken swap.
close #108

Access to Awaken swap

---

src/TomorrowDAOServer.Application.Contracts/Common/MapHelper.cs
src/TomorrowDAOServer.Application.Contracts/Options/NetworkDaoOptions.cs
src/TomorrowDAOServer.Application.Contracts/ThirdPart/Exchange/AbstractExchangeProvider.cs
src/TomorrowDAOServer.Application.Contracts/ThirdPart/Exchange/AetherLinkProvider.cs
src/TomorrowDAOServer.Application.Contracts/ThirdPart/Exchange/AwakenProvider.cs
src/TomorrowDAOServer.Application.Contracts/ThirdPart/Exchange/IExchangeProvider.cs
src/TomorrowDAOServer.Application.Contracts/Token/ITokenService.cs
src/TomorrowDAOServer.Application.Contracts/TomorrowDAOServer.Application.Contracts.csproj
src/TomorrowDAOServer.Application.Contracts/TomorrowDAOServerApplicationContractsModule.cs
src/TomorrowDAOServer.Application/Token/TokenPriceUpdateService.cs
src/TomorrowDAOServer.Application/Token/TokenService.cs
src/TomorrowDAOServer.Application/TomorrowDAOServerApplicationModule.cs
src/TomorrowDAOServer.AuthServer/TomorrowDAOServer.AuthServer.csproj
src/TomorrowDAOServer.DbMigrator/TomorrowDAOServer.DbMigrator.csproj
src/TomorrowDAOServer.Domain.Shared/TomorrowDAOServer.Domain.Shared.csproj
src/TomorrowDAOServer.EntityEventHandler/TomorrowDAOServer.EntityEventHandler.csproj
src/TomorrowDAOServer.EntityEventHandler/appsettings.json
src/TomorrowDAOServer.Grains/TomorrowDAOServer.Grains.csproj
src/TomorrowDAOServer.HttpApi.Host/TomorrowDAOServer.HttpApi.Host.csproj
src/TomorrowDAOServer.HttpApi/TomorrowDAOServer.HttpApi.csproj
src/TomorrowDAOServer.Silo/TomorrowDAOServer.Silo.csproj
test/TomorrowDAOServer.Application.Contracts.Tests/TomorrowDAOServer.Application.Contracts.Tests.csproj
test/TomorrowDAOServer.Application.Tests/Token/TokenPriceUpdateServiceTest.cs
test/TomorrowDAOServer.Application.Tests/TomorrowDAOServer.Application.Tests.csproj
test/TomorrowDAOServer.Grains.Tests/TomorrowDAOServer.Grains.Tests.csproj
test/TomorrowDAOServer.Orleans.TestBase/TomorrowDAOServer.Orleans.TestBase.csproj

Support token price from Aether Link.
close #112

Access to aether link

---

src/TomorrowDAOServer.Application.Contracts/Proposal/Dto/IndexerVoteHistoryDto.cs
src/TomorrowDAOServer.Application.Contracts/Proposal/Dto/ProposalDetailDto.cs
src/TomorrowDAOServer.Application.Contracts/Proposal/Dto/VoteHistoryDto.cs
src/TomorrowDAOServer.Application.Contracts/Proposal/IProposalService.cs
src/TomorrowDAOServer.Application.Contracts/Token/ITokenService.cs
src/TomorrowDAOServer.Application/Proposal/ProposalService.cs
src/TomorrowDAOServer.Application/Proposal/Provider/ProposalProvider.cs
src/TomorrowDAOServer.Application/Token/TokenService.cs
src/TomorrowDAOServer.Application/TomorrowDAOServerApplicationAutoMapperProfile.cs
src/TomorrowDAOServer.Application/Vote/Provider/VoteProvider.cs
src/TomorrowDAOServer.HttpApi/Controllers/ProposalController.cs
test/TomorrowDAOServer.Application.Tests/Proposal/ProposalServiceTest.cs

Handle decimals for /api/app/proposal/vote-history's vote amount when TOKEN_BALLOT.
close #107

Vote result optimization

---

src/TomorrowDAOServer.Application/Token/TokenService.cs

Fix average price calculate problem

Fix average price calculate problem

---

src/TomorrowDAOServer.Application.Contracts/DAO/Dtos/DAOListDto.cs
src/TomorrowDAOServer.Application.Contracts/DAO/Dtos/QueryDAOListInput.cs
src/TomorrowDAOServer.Application.Contracts/DAO/Dtos/QueryMyDAOListInput.cs
src/TomorrowDAOServer.Application.Contracts/DAO/Dtos/QueryPageInput.cs
src/TomorrowDAOServer.Application.Contracts/Options/DaoOptions.cs
src/TomorrowDAOServer.Application/DAO/DAOAppService.cs
src/TomorrowDAOServer.Application/DAO/Provider/DAOProvider.cs
src/TomorrowDAOServer.Application/Proposal/Provider/ProposalProvider.cs
src/TomorrowDAOServer.Application/ScheduleSyncDataService.cs
src/TomorrowDAOServer.Domain.Shared/Enums/DAOType.cs
src/TomorrowDAOServer.Domain.Shared/Enums/VerifiedType.cs
src/TomorrowDAOServer.HttpApi.Host/TomorrowDAOServerHttpApiHostModule.cs
src/TomorrowDAOServer.HttpApi.Host/appsettings.json
test/TomorrowDAOServer.Application.Tests/DAO/DAOAppServiceTests.cs
test/TomorrowDAOServer.Application.Tests/DAO/DaoAppServiceTest.cs
test/TomorrowDAOServer.Application.Tests/Proposal/Provider/ProposalProviderTest.cs
test/TomorrowDAOServer.Application.Tests/TomorrowDAOServerApplicationTestBase.cs

Support DAO list sort and verified.
#133

DAO list sort and verification

---

src/TomorrowDAOServer.Application.Contracts/Token/Dto/TvlDetail.cs
src/TomorrowDAOServer.Application.Contracts/Token/ITokenService.cs
src/TomorrowDAOServer.Application/Token/TokenService.cs
src/TomorrowDAOServer.HttpApi/Controllers/TokenController.cs
test/TomorrowDAOServer.Application.Tests/Token/TokenServiceTest.cs

Split TVL by token dimension.
#182

TVL break down

---

src/TomorrowDAOServer.Application.Contracts/TomorrowDAOServer.Application.Contracts.csproj
src/TomorrowDAOServer.EntityEventHandler/appsettings.json

Support AetherLink update.
#196

Support AetherLink update

---

src/TomorrowDAOServer.Application/Ranking/RankingAppService.cs

1. Fix the expired list point in the problem. #217

Votigram Like issue

---

src/TomorrowDAOServer.Application.Contracts/Options/RankingOptions.cs
src/TomorrowDAOServer.Application.Contracts/Ranking/Dto/RankingDetailDto.cs
src/TomorrowDAOServer.Application.Contracts/Ranking/Dto/RankingListDto.cs
src/TomorrowDAOServer.Application/Proposal/ProposalService.cs
src/TomorrowDAOServer.Application/Proposal/Provider/ProposalProvider.cs
src/TomorrowDAOServer.Application/Ranking/RankingAppService.cs
src/TomorrowDAOServer.Application/TomorrowDAOServerApplicationAutoMapperProfile.cs
src/TomorrowDAOServer.AuthServer/SignatureGrantHandler.cs
src/TomorrowDAOServer.Domain.Shared/Enums/RankingType.cs
test/TomorrowDAOServer.Application.Tests/Ranking/RankingAppServiceTestMock.cs
test/TomorrowDAOServer.Application.Tests/Telegram/TelegramServiceTest.cs

Votigram ranking list optimization
#222 #225

ranking list optimization

---

src/TomorrowDAOServer.Application.Contracts/Common/Dtos/AppPageResultDto.cs
src/TomorrowDAOServer.Application.Contracts/Ranking/Dto/RankingBannerInfo.cs
src/TomorrowDAOServer.Application.Contracts/Ranking/Dto/RankingListDto.cs
src/TomorrowDAOServer.Application.Contracts/Ranking/IRankingAppService.cs
src/TomorrowDAOServer.Application.Contracts/Referral/Dto/InviteDetailDto.cs
src/TomorrowDAOServer.Application/Discover/DiscoverService.cs
src/TomorrowDAOServer.Application/Proposal/Provider/ProposalProvider.cs
src/TomorrowDAOServer.Application/Proposal/TopProposalGenerateService.cs
src/TomorrowDAOServer.Application/Ranking/RankingAppService.cs
src/TomorrowDAOServer.Application/Referral/ReferralService.cs
src/TomorrowDAOServer.Application/Spider/FindminiAppsSyncDataService.cs
src/TomorrowDAOServer.Application/Telegram/Provider/TelegramAppsProvider.cs
src/TomorrowDAOServer.Application/User/Provider/UserViewAppProvider.cs
src/TomorrowDAOServer.HttpApi/Controllers/RankingController.cs

Votigram bubble

---

src/TomorrowDAOServer.Application/TomorrowDAOServerApplicationAutoMapperProfile.cs

Fix icon prefix

---

src/TomorrowDAOServer.Application.Contracts/Common/CommonConstant.cs
src/TomorrowDAOServer.Application.Contracts/Common/InformationHelper.cs
src/TomorrowDAOServer.Application.Contracts/Common/Sha256HashHelper.cs
src/TomorrowDAOServer.Application.Contracts/Common/UserTaskHelper.cs
src/TomorrowDAOServer.Application.Contracts/Options/RankingOptions.cs
src/TomorrowDAOServer.Application.Contracts/Options/UserOptions.cs
src/TomorrowDAOServer.Application.Contracts/User/Dtos/ViewAdInput.cs
src/TomorrowDAOServer.Application.Contracts/User/IUserService.cs
src/TomorrowDAOServer.Application/Discover/DiscoverService.cs
src/TomorrowDAOServer.Application/Proposal/Provider/ProposalProvider.cs
src/TomorrowDAOServer.Application/Ranking/Provider/RankingAppPointsCalcProvider.cs
src/TomorrowDAOServer.Application/Ranking/Provider/RankingAppPointsRedisProvider.cs
src/TomorrowDAOServer.Application/Ranking/RankingAppService.cs
src/TomorrowDAOServer.Application/User/Provider/UserPointsRecordProvider.cs
src/TomorrowDAOServer.Application/User/UserService.cs
src/TomorrowDAOServer.Domain.Shared/Enums/AdPlatform.cs
src/TomorrowDAOServer.Domain.Shared/Enums/PointsType.cs
src/TomorrowDAOServer.Domain.Shared/Enums/UserTaskDetail.cs
src/TomorrowDAOServer.Grains/Grain/Users/UserViewAdTimeStampGrain.cs
src/TomorrowDAOServer.Grains/State/Users/UserViewAdTimeStampState.cs
src/TomorrowDAOServer.HttpApi.Host/appsettings.json
src/TomorrowDAOServer.HttpApi/Controllers/UserController.cs
test/TomorrowDAOServer.Application.Tests/Ranking/Provider/RankingAppPointsCalcProviderTest.cs
test/TomorrowDAOServer.Application.Tests/Ranking/RankingAppServiceTestMock.cs

votigram ad

---

src/TomorrowDAOServer.Application.Contracts/Dtos/Explorer/ExplorerProposalResult.cs

Fix Network DAO Proposal list issue

---

src/TomorrowDAOServer.Application.Contracts/Common/Dtos/LuckboxResponse.cs
src/TomorrowDAOServer.Application.Contracts/Common/Dtos/LuckyboxRequest.cs
src/TomorrowDAOServer.Application.Contracts/Common/HMACSHA256Helper.cs
src/TomorrowDAOServer.Application.Contracts/Options/DiscoverOptions.cs
src/TomorrowDAOServer.Application.Contracts/Options/LuckyboxOptions.cs
src/TomorrowDAOServer.Application.Contracts/Ranking/Dto/RankingVote.cs
src/TomorrowDAOServer.Application.Contracts/Telegram/Dto/AddAppInput.cs
src/TomorrowDAOServer.Application.Contracts/Telegram/ITelegramService.cs
src/TomorrowDAOServer.Application/Discover/DiscoverService.cs
src/TomorrowDAOServer.Application/Luckybox/LuckyboxTaskCompleteService.cs
src/TomorrowDAOServer.Application/Luckybox/Provider/LuckboxTaskProvider.cs
src/TomorrowDAOServer.Application/Luckybox/Provider/LuckyboxApiProvider.cs
src/TomorrowDAOServer.Application/Ranking/RankingAppService.cs
src/TomorrowDAOServer.Application/Telegram/Provider/TelegramAppsProvider.cs
src/TomorrowDAOServer.Application/Telegram/TelegramService.cs
src/TomorrowDAOServer.Application/TomorrowDAOServerApplicationModule.cs
src/TomorrowDAOServer.AuthServer/SignatureGrantHandler.cs
src/TomorrowDAOServer.Domain.Shared/Enums/WorkerBusinessType.cs
src/TomorrowDAOServer.Domain/Entities/LuckyBoxTaskIndex.cs
src/TomorrowDAOServer.EntityEventHandler/TomorrowDAOServerEntityEventHandlerModule.cs
src/TomorrowDAOServer.EntityEventHandler/appsettings.json
src/TomorrowDAOServer.HttpApi.Host/TomorrowDAOServerHttpApiHostModule.cs
src/TomorrowDAOServer.HttpApi.Host/appsettings.json
src/TomorrowDAOServer.HttpApi/Controllers/TelegramController.cs
src/TomorrowDAOServer.Worker/Jobs/LuckyboxTaskCompleteWorker.cs
src/TomorrowDAOServer.Worker/TomorrowDAOServerWorkerModule.cs

Votigram lucky box

---

src/TomorrowDAOServer.AuthServer/TomorrowDAOServer.AuthServer.csproj

Openiddict issue

---

src/TomorrowDAOServer.Application/Proposal/ProposalService.cs
test/TomorrowDAOServer.Application.Contracts.Tests/Common/ExpressionHelperTest.cs
test/TomorrowDAOServer.Application.Contracts.Tests/TomorrowDAOServerApplicationContractsTestsModule.cs
test/TomorrowDAOServer.Application.Tests/Common/Mocks/GraphQLClientMock.cs
test/TomorrowDAOServer.Application.Tests/Common/Provider/AElfClientProviderTest.cs
test/TomorrowDAOServer.Application.Tests/Common/Provider/GraphQlPrividerTest.cs
test/TomorrowDAOServer.Application.Tests/Contract/ScriptServiceTest.cs
test/TomorrowDAOServer.Application.Tests/Contract/TransactionServiceTest.cs
test/TomorrowDAOServer.Application.Tests/Contract/TransactionServiceTestMock.cs
test/TomorrowDAOServer.Application.Tests/DAO/Provider/DAOProviderTest.cs
test/TomorrowDAOServer.Application.Tests/DAO/Provider/DaoAliasProviderTest.cs
test/TomorrowDAOServer.Application.Tests/MQ/MessagePublisherServiceTest.cs
test/TomorrowDAOServer.Application.Tests/NetworkDao/NetworkDaoElectionServiceTest.cs
test/TomorrowDAOServer.Application.Tests/Ranking/Provider/RankingAppPointsCalcProviderTest.cs
test/TomorrowDAOServer.Application.Tests/Ranking/RankingAppServiceVoteTest.cs
test/TomorrowDAOServer.Application.Tests/Spider/TelegramAppsSpiderServiceTest.cs
test/TomorrowDAOServer.Application.Tests/Treasury/TreasuryAssetsServiceTest.cs
test/TomorrowDAOServer.Application.Tests/User/Provider/UserProviderTest.cs
test/TomorrowDAOServer.Application.Tests/Vote/Provider/VoteProviderTest.cs

[WIP] Fix the unit testing issues after Server upgrade

---

src/TomorrowDAOServer.Application.Contracts/Common/CommonConstant.cs
src/TomorrowDAOServer.Application/TonGift/Provider/TonGiftApiProvider.cs
src/TomorrowDAOServer.AuthServer/appsettings.json
src/TomorrowDAOServer.DbMigrator/appsettings.json
src/TomorrowDAOServer.EntityEventHandler/appsettings.json
src/TomorrowDAOServer.HttpApi.Host/appsettings.json
src/TomorrowDAOServer.Silo/appsettings.json
test/TomorrowDAOServer.Application.Tests/TomorrowDAOServerApplicationTestBase.cs
test/TomorrowDAOServer.TestBase/Common/TestConstant.cs

Optimize the use of private keys in unit testing

---

src/TomorrowDAOServer.Application.Contracts/Open/IOpenService.cs
src/TomorrowDAOServer.Application.Contracts/Options/Micro3Options.cs
src/TomorrowDAOServer.Application/Open/OpenService.cs
src/TomorrowDAOServer.HttpApi/Controllers/OpenController.cs

Votigram Galxe

---

src/TomorrowDAOServer.Application/Discover/DiscoverService.cs
src/TomorrowDAOServer.Application/Ranking/Provider/RankingAppProvider.cs
src/TomorrowDAOServer.HttpApi/Controllers/DiscoverController.cs

fix: ranking app list search

---

src/TomorrowDAOServer.Application/Discover/DiscoverService.cs

fix: can vote

---

src/TomorrowDAOServer.Application.Contracts/Ranking/Dto/RankingVote.cs
src/TomorrowDAOServer.Application/Ranking/RankingAppService.cs

fix: add userTotalPoints

---

src/TomorrowDAOServer.Application.Contracts/Ranking/Dto/RankingAppDetailDto.cs
src/TomorrowDAOServer.Application/Ranking/RankingAppService.cs
src/TomorrowDAOServer.Application/User/UserService.cs

fix: pointsPercent

---

src/TomorrowDAOServer.Application/Ranking/Provider/RankingAppProvider.cs

fix: GetRankingAppListAsync

---

src/TomorrowDAOServer.Application/Discover/DiscoverService.cs

fix: GetAccumulativeAppList

---

src/TomorrowDAOServer.Application/Ranking/Provider/RankingAppPointsRedisProvider.cs

fix: Increment Amount Add Log

---

src/TomorrowDAOServer.Application/User/UserService.cs

fix:add log

---

src/TomorrowDAOServer.Application.Contracts/Ranking/Dto/GetRankingAppListInput.cs
src/TomorrowDAOServer.Application/Discover/DiscoverService.cs
src/TomorrowDAOServer.Application/Ranking/Provider/RankingAppProvider.cs

fix: points percent

---

src/TomorrowDAOServer.Application/Discover/DiscoverService.cs

fix: sort by

---

src/TomorrowDAOServer.Application/User/UserService.cs

fix: default category

---

src/TomorrowDAOServer.Application/Discover/DiscoverService.cs

fix: remove random list

---

src/TomorrowDAOServer.Application/Ranking/RankingAppService.cs

fix : filter telegram app null fields

fix : filter telegram app null fields

---

src/TomorrowDAOServer.Application/Discover/DiscoverService.cs
src/TomorrowDAOServer.Application/Ranking/RankingAppService.cs

fix: total count

---

src/TomorrowDAOServer.Application/User/UserService.cs

fix: task list

---

src/TomorrowDAOServer.Application/Telegram/Provider/TelegramAppsProvider.cs
src/TomorrowDAOServer.AuthServer/Options/TelegramAuthOptions.cs

fix: search by all

---

src/TomorrowDAOServer.Application/Telegram/Provider/TelegramAppsProvider.cs

fix: Fuzziness search

---

src/TomorrowDAOServer.Application.Contracts/Options/RankingOptions.cs
src/TomorrowDAOServer.Application/User/UserService.cs

feat: hidden game

---

src/TomorrowDAOServer.Application.Contracts/User/IUserAppService.cs
src/TomorrowDAOServer.Application.Contracts/User/IUserService.cs
src/TomorrowDAOServer.Application/User/UserAppService.cs
src/TomorrowDAOServer.Application/User/UserService.cs
src/TomorrowDAOServer.HttpApi/Controllers/UserController.cs

feat: get user points

---

src/TomorrowDAOServer.Application/User/UserService.cs

fix: group by

---

src/TomorrowDAOServer.Application/User/UserService.cs

fix: filter create time max

---

src/TomorrowDAOServer.Application.Contracts/User/Dtos/GetAllUserPointsInput.cs
src/TomorrowDAOServer.Application.Contracts/User/IUserService.cs
src/TomorrowDAOServer.Application/User/Provider/UserProvider.cs
src/TomorrowDAOServer.Application/User/UserAppService.cs
src/TomorrowDAOServer.Application/User/UserService.cs
src/TomorrowDAOServer.HttpApi/Controllers/UserController.cs

User points distribution

---

scripts/grafana/dashboard_prod_login_user_day.sh
scripts/grafana/dashboard_prod_visit_user_day.sh
src/TomorrowDAOServer.Application/Discover/DiscoverService.cs
src/TomorrowDAOServer.Application/Discussion/Provider/DiscussionProvider.cs
src/TomorrowDAOServer.Application/Ranking/Provider/RankingAppPointsRedisProvider.cs
src/TomorrowDAOServer.Application/Ranking/Provider/RankingAppProvider.cs
src/TomorrowDAOServer.Application/Telegram/Provider/TelegramAppsProvider.cs
src/TomorrowDAOServer.Application/Telegram/TelegramService.cs
src/TomorrowDAOServer.Application/TomorrowDAOServerApplicationAutoMapperProfile.cs
src/TomorrowDAOServer.Domain/Entities/RankingAppIndex.cs
src/TomorrowDAOServer.Domain/Entities/TelegramAppIndex.cs
src/TomorrowDAOServer.Grains/Grain/Users/UserGrain.cs
test/TomorrowDAOServer.Application.Tests/Discover/DiscoverServiceTest.cs
test/TomorrowDAOServer.Application.Tests/Ranking/Provider/RankingAppPointsRedisProviderTestMock.cs
test/TomorrowDAOServer.Application.Tests/User/UserServiceTestMock.cs
test/TomorrowDAOServer.Grains.Tests/Grain/Users/UserGrainTest.cs

1.Fuzzy search on the Discover page. #365

Fuzzy search

---

src/TomorrowDAOServer.Application.Contracts/Common/Security/RedisHelper.cs
src/TomorrowDAOServer.Application.Contracts/MQ/IMessagePublisherService.cs
src/TomorrowDAOServer.Application.Contracts/Options/RankingOptions.cs
src/TomorrowDAOServer.Application.Contracts/Ranking/Eto/VoteAndLikeMessageEto.cs
src/TomorrowDAOServer.Application/MQ/MessagePublisherService.cs
src/TomorrowDAOServer.Application/Ranking/Provider/RankingAppPointsRedisProvider.cs
src/TomorrowDAOServer.Application/Ranking/RankingAppService.cs
src/TomorrowDAOServer.Domain/Entities/RankingAppUserPointsIndex.cs

feat: daily get points limit

---

scripts/grafana/dashboard_prod_login_user_hour.sh
src/TomorrowDAOServer.Application.Contracts/Common/Security/RedisHelper.cs
src/TomorrowDAOServer.Application.Contracts/Discover/Dto/DiscoverAppDto.cs
src/TomorrowDAOServer.Application.Contracts/MQ/IMessagePublisherService.cs
src/TomorrowDAOServer.Application.Contracts/Ranking/Dto/RankingAppDetailDto.cs
src/TomorrowDAOServer.Application.Contracts/Telegram/Dto/AppDetailDto.cs
src/TomorrowDAOServer.Application.Contracts/Telegram/Dto/GetTelegramAppInput.cs
src/TomorrowDAOServer.Application.Contracts/Telegram/Dto/TelegramAppDto.cs
src/TomorrowDAOServer.Application.Contracts/Telegram/ITelegramService.cs
src/TomorrowDAOServer.Application.Contracts/User/Dtos/ShareAppInput.cs
src/TomorrowDAOServer.Application.Contracts/User/IUserService.cs
src/TomorrowDAOServer.Application/Contract/ScriptService.cs
src/TomorrowDAOServer.Application/Discover/DiscoverService.cs
src/TomorrowDAOServer.Application/MQ/MessagePublisherService.cs
src/TomorrowDAOServer.Application/Ranking/Provider/RankingAppPointsRedisProvider.cs
src/TomorrowDAOServer.Application/Telegram/TelegramService.cs
src/TomorrowDAOServer.Application/TomorrowDAOServerApplicationAutoMapperProfile.cs
src/TomorrowDAOServer.Application/User/UserService.cs
src/TomorrowDAOServer.Domain.Shared/Enums/PointsType.cs
src/TomorrowDAOServer.EntityEventHandler.Core/MQ/VoteAndLikeMessageHandler.cs
src/TomorrowDAOServer.HttpApi/Controllers/TelegramController.cs
src/TomorrowDAOServer.HttpApi/Controllers/UserController.cs
test/TomorrowDAOServer.Application.Tests/Telegram/TelegramServiceTest.cs

Add share feature to foryou page

---

src/TomorrowDAOServer.Application.Contracts/Common/MapHelper.cs
src/TomorrowDAOServer.Application/TomorrowDAOServerApplicationAutoMapperProfile.cs
test/TomorrowDAOServer.Application.Tests/Proposal/Provider/ProposalProviderTestNew.cs
test/TomorrowDAOServer.Application.Tests/Providers/PortkeyProviderTest.cs
test/TomorrowDAOServer.Application.Tests/Providers/PortkeyProviderTestMock.cs
test/TomorrowDAOServer.Application.Tests/Ranking/Provider/RankingAppPointsRedisProviderTest.cs
test/TomorrowDAOServer.Application.Tests/TomorrowDAOServerApplicationTestBase.cs
test/TomorrowDAOServer.Application.Tests/User/UserServiceTest.cs

TMRW DAO Revamp

---

src/TomorrowDAOServer.Application.Contracts/NetworkDao/Dtos/GetAllPersonalVotesInput.cs
src/TomorrowDAOServer.Application.Contracts/NetworkDao/Dtos/GetPersonalVotesInput.cs
src/TomorrowDAOServer.Application.Contracts/NetworkDao/Dtos/UpdateVoteReclaimInput.cs
src/TomorrowDAOServer.Application.Contracts/NetworkDao/INetworkDaoVoteService.cs
src/TomorrowDAOServer.Application.Contracts/NetworkDao/Migrator/ES/GetVotedListInput.cs
src/TomorrowDAOServer.Application.Contracts/NetworkDao/Options/MigratorOptions.cs
src/TomorrowDAOServer.Application/NetworkDao/NetworkDaoVoteService.cs
src/TomorrowDAOServer.Application/NetworkDao/Provider/NetworkDaoEsDataProvider.cs
src/TomorrowDAOServer.Application/NetworkDao/Sync/NetworkDaoProposalSyncService.cs
src/TomorrowDAOServer.Application/TomorrowDAOServerApplicationAutoMapperProfile.cs
src/TomorrowDAOServer.Domain/NetworkDao/NetworkDaoProposalVoteIndex.cs
src/TomorrowDAOServer.HttpApi/Controllers/NetworkDaoController.cs

Optimize NetworkDAO Interfaces
